name: RMBNametags
version: '${project.version}'
main: me.vewa.rmbnametags.RMBNametags
api-version: '1.21'
description: A plugin to hide player names and show them on right-click in actionbar
softdepend: ["PlaceholderAPI"]
commands:
  rmbnametags:
    description: Manage nametags
    usage: /<command> [reload|hide|show]
permissions:
  rmbnametags.reload:
    description: Permission to reload config
    default: op
  rmbnametags.hide-show:
    description: Permission to hide or show own nametag
    default: true
  rmbnametags.hide-show.other:
    description: Permission to hide or show other players nametags
    default: op
  rmbnametags.hide.custom:
    description: Permission to set custom names when hiding
    default: op
